# Generated by Django 5.2 on 2026-03-29 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_saleitem_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
