# Generated by Django 5.2 on 2026-03-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_sale_amount_paid_sale_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('card', 'Card')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
